# docker compose up -d --build
# docker compose down

# Our entire services (containers)
services:

  # MySQL service: 
  mysql-service:

    # Download the following image from DockerHub:
    image: mysql:8

    # What is the container name: 
    container_name: mysql-container

    # Environment variables needed by mysql:8: 
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: JohnBryce
      MYSQL_PASSWORD: Pa$$w0rd
      MYSQL_DATABASE: northwind
      MYSQL_ROOT_PASSWORD: Pa$$w0rd

    # Volumes:
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./Database/MySQL:/docker-entrypoint-initdb.d

    # Restart policy - when to restart the container:
    restart: unless-stopped

    # Constantly check if our server works:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

# ---------------------------------------------------------------------------------------------------

  # MongoDB service:
  mongo-service:

    # Download the following image from DockerHub:
    image: mongo:8

    # What is the container name: 
    container_name: mongo-container

    # Volumes:
    volumes:
      - mongo-volume:/data/db
      - ./Database/Mongo:/docker-entrypoint-initdb.d

    # Restart policy - when to restart the container:
    restart: unless-stopped

    # Constantly check if our server works:
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

# ---------------------------------------------------------------------------------------------------

  # Our northwind backend:
  backend-service:

    # Which other services we're depending on - we need to wait:
    depends_on:
      mysql-service:
        condition: service_healthy
      mongo-service:
        condition: service_healthy

    # Build context - what it the current folder:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile

    # What is the image name: 
    image: assaffink/backend-image:1.0

    # What is the container name: 
    container_name: backend-container

    # Environment variables needed by our backend:
    environment:
      MYSQL_HOST: mysql-service # Service name is the name of the "computer" we need to connect
      MYSQL_USER: JohnBryce
      MYSQL_PASSWORD: Pa$$w0rd
      MYSQL_DATABASE: northwind
      MONGO_CONNECTION_STRING: mongodb://mongo-service:27017/northwind

    # Port mapping (hostPort:containerPort)
    ports:
      - 4000:4000

    # Volumes:
    volumes:
      - images-volume:/app/src/1-assets/images # Named Volume

    # Restart policy - when to restart the container:
    restart: unless-stopped

    # Constantly check if our server works:
    healthcheck:
      test: ["CMD", "node", "--eval", "require('http').get('http://localhost:4000/ping', response => process.exit(response.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

# ---------------------------------------------------------------------------------------------------

  # Our frontend website: 
  frontend-service:

    # Which other services we're depending on - we need to wait:
    depends_on:
      backend-service:
        condition: service_healthy

    # Build context - what it the current folder:
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile

    # What is the image name: 
    image: assaffink/frontend-image:1.0

    # What is the container name: 
    container_name: frontend-container

    # Port mapping (hostPort:containerPort)
    ports:
      - 80:5173

    # Restart policy - when to restart the container:
    restart: unless-stopped

    # Constantly check if our server works:
    healthcheck:
      test: ["CMD", "node", "--eval", "require('http').get('http://localhost:5173', response => process.exit(response.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

# ---------------------------------------------------------------------------------------------------

# List all named-volumes we're using: 
volumes:
  mysql-volume:
  mongo-volume:
  images-volume:
